function(conditional_replace VAR1 VAR2 DEFAULT TYPE DESC)
   if(NOT ${VAR1})
      if (NOT ${VAR2})
         set(${VAR2} ${DEFAULT} CACHE ${TYPE} ${DESC} FORCE)
      else()
         set(${VAR2} ${${VAR2}} CACHE ${TYPE} ${DESC} FORCE)
      endif()
   else()
      set(${VAR2} ${${VAR2}} CACHE INTERNAL "")
   endif()
endfunction()

function(validate_option VAR AVAILABLE DEFAULT TYPE DESC)
   set(found FALSE)
   foreach(item ${${AVAILABLE}})
      string(COMPARE EQUAL ${${VAR}} ${item} equals)
      if(equals)
         set(found TRUE)
         break()
      endif()
   endforeach()

   if(NOT found)
      message("Your input of " ${${VAR}} " for " ${VAR} " is not in the allowed list")
      message("Allowed options are: ")
      foreach(item ${${AVAILABLE}})
         message(${item})
      endforeach()
      message("Resetting " ${VAR} " to the default: " ${DEFAULT})
      set(${VAR} ${DEFAULT} CACHE ${TYPE} ${DESC} FORCE)
   else()
         set(${VAR} ${${VAR}} CACHE ${TYPE} ${DESC} FORCE)
   endif()
endfunction()

function(conditional_replace_validate VAR1 ONOFF VAR2 AVAILABLE DEFAULT TYPE DESC)
   if(${VAR1} STREQUAL ${ONOFF})
      if (NOT ${VAR2})
         set(${VAR2} ${DEFAULT} CACHE ${TYPE} ${${DESC}} FORCE)
      else()
         validate_option(${VAR2} ${AVAILABLE} ${DEFAULT} ${TYPE} ${${DESC}})
      endif()
   else()
      set(${VAR2} ${${VAR2}} CACHE INTERNAL "")
   endif()
endfunction()
